# Generated by Django 3.1.2 on 2020-10-09 11:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('nacimiento', models.DateField(blank=True, null=True)),
                ('desarrolladora', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingresa el género del videojuego.', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Videojuego',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('resumen', models.TextField(help_text='Ingresa un breve resumen del videojuego.', max_length=1000)),
                ('director', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.director')),
                ('genero', models.ManyToManyField(help_text='Selecciona un género.', to='catalogo.Genero')),
            ],
        ),
        migrations.CreateModel(
            name='Disponibilidad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID único para el videojuego.', primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, choices=[('di', 'Disponible'), ('de', 'Desarrollo'), ('r', 'Reservado')], default='di', help_text='Disponibilidad del juego.', max_length=2)),
                ('videojuego', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.videojuego')),
            ],
        ),
    ]
